import multer from "multer";
export const hostDomainName = process.env.HOST_DOMAIN_NAME;
export const port = process.env.PORT;
export const googleOAuthClientId = process.env.GOOGLE_OAUTH_CLIENT_ID;
export const googleOAuthClientSecret = process.env.GOOGLE_OAUTH_CLIENT_SECRET;
export const nodeEnv = process.env.NODE_ENV;
export const dbHost = process.env.DB_HOST;
export const dbName = process.env.DB_DATABASE;
export const dbUser = process.env.DB_USER;
export const dbPass = process.env.DB_PASS;
export const cryptoPasswordKey = process.env.CRYPTO_PASSWORD_KEY;
export const cryptoPasswordIV = process.env.CRYPTO_PASSWORD_IV;
export const jwtSecretKet = process.env.JWT_SECRET_KEY;
export const multerUpload = multer();
export const cloudinaryApiKey = process.env.CLOUDINARY_API_KEY;
export const cloudinarySecretKey = process.env.CLOUDINARY_SECRET_KEY;
export const nodemailerUser = process.env.NODEMAILER_USER;
export const nodemailerPass = process.env.NODEMAILER_PASS;
